
import { Product, Suppliers, SupplierKey } from './types';

export const DEFAULT_AXION_ITEMS: Product[] = [
    { id: 'aceite_fritura', name: 'ACEITE FRITURA', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'almibar_factura', name: 'ALMIBAR PARA FACTURA X 7 KG', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'azucar_individual', name: 'AZUCAR INDIVIDUAL KFC', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'bandeja_canoa', name: 'BANDEJA CANOA KFC', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'bolsa_llevar_grande', name: 'BOLSA DE LLEVAR GRANDE KFC2', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'bolsa_residuos_chica', name: 'BOLSA DE RESIDUOS CHICA', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'bolsa_residuos_grande', name: 'BOLSA DE RESIDUOS GRANDE', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'bolsa_residuos_negra', name: 'BOLSA DE RESIDUOS NEGRA X 250 UND', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'bolsa_residuos_transparente', name: 'BOLSA DE RESIDUOS TRANSPARENTE', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'bolsa_residuos_verde', name: 'BOLSA DE RESIDUOS VERDE', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'bolsa_marinado_k', name: 'BOLSA PARA MARINADO K EN ROLLOS', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'bolsa_sin_manija_grande', name: 'BOLSA SIN MANIJA GRANDE KFC X 250 UND', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'bucket_130oz', name: 'BUCKET 130OZ KFC X 300UN', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'bucket_50oz', name: 'BUCKET 50OZ', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'bucket_85oz', name: 'BUCKET 85OZ X 330 UND', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'cafe_polvo', name: 'CAFE EN POLVO', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'caja_big_box', name: 'CAJA BIG BOXKFC', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'caja_snack_tapa', name: 'CAJA SNACK CON TAPA KFC X 800 UND', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'candaditos_kfc', name: 'CANDADITOS KFC', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'chocolate_mani', name: 'CHOCOLATE CON MANI X 4.32KG', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'chocolate_polvo', name: 'CHOCOLATE EN POLVO X 4KG', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'cinta_seguridad', name: 'CINTA DE SEGURIDAD KFC X 36 UND', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'cofia_fiselina', name: 'COFIA DE FISELINA DESCARTABLE', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'cono_helado', name: 'CONO HELADO', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'cucharita_helado', name: 'CUCHARITA PARA HELADO X 1000 UND', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'cuchillo', name: 'CUCHILLO', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'dipper', name: 'DIPPER', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'edulcorante_individual', name: 'EDULCORANTE INDIVIDUAL KFC', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'estuche_papa_chica', name: 'ESTUCHE PAPA CHICA KFC X 800 UND', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'estuche_papas_grandes', name: 'ESTUCHE PAPAS GRANDES KFC', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'estuche_papas_medianas', name: 'ESTUCHE PAPAS MEDIANAS KFC', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'estuche_popcorn_grande', name: 'ESTUCHE POPCORN GRANDE', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'estuche_popcorn_mediano', name: 'ESTUCHE POPCORN MEDIANO', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'etc_tempero', name: 'ETC TEMPERO', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'etc_tempero_5kg', name: 'ETC TEMPERO 5KG', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'etiquet_sobres_proseg', name: 'ETIQUET SOBRES PROSEG X1000U', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'etiquetas', name: 'ETIQUETAS', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'etiquetas_seguridad_kfc', name: 'ETIQUETAS DE SEGURIDAD KFC', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'etiquetas_seguridad_4800', name: 'ETIQUETAS SEGURIDAD X 4800 UND', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'filtro_frymaster', name: 'FILTRO FREIDORAS FRYMASTER', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'filtro_henny_penny', name: 'FILTRO FREIDORAS HENNY PENNY', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'galletita_oreo', name: 'GALLETITA OREO CAJA X36 X 117 GR', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'guacamole', name: 'GUACAMOLE', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'guantes_vinilo_m', name: 'GUANTES VINILO M', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'harina_11kg', name: 'HARINA X 11.389KG', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'helado_ddl', name: 'HELADO DULCE DE LECHE', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'helado_vainilla', name: 'HELADO VAINILLA', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'jarabe_frutilla', name: 'JARABE DE FRUTILLA', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'jugo_limon_individual', name: 'JUGO DE LIMON INDIVIDUAL', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'ketchup_individual', name: 'KETCHUP INDIVIDUAL', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'kit_cartel_acrilico', name: 'KIT CARTEL ACRILICO A4', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'kit_filtros_agua', name: 'KIT FILTROS DE AGUA', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'kit_lamparas_papas', name: 'KIT LAMPARAS PARA PAPAS', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'kit_tabla_blanca', name: 'KIT TABLA BLANCA', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'kit_tabla_roja', name: 'KIT TABLA ROJA', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'kit_tabla_verde', name: 'KIT TABLA VERDE', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'kit_taylor_359', name: 'KIT TAYLOR 359 (FROSTY)', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'kit_taylor_708', name: 'KIT TAYLOR 708 (SOFT)', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'kit_taylor_716', name: 'KIT TAYLOR 716 (SOFT)', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'lamina_antigrasa_sandwich', name: 'LAMINA ANTIGRASA SANDWICH KFC X1500', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'leche_polvo', name: 'LECHE EN POLVO CAJAX10KG', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'lomito_fetas', name: 'LOMITO EN FETAS', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'mandolina', name: 'MANDOLINA', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'manteca_6kg', name: 'MANTECA X 6KG', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'mantecol', name: 'MANTECOL', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'mantelito_kfc', name: 'MANTELITO KFC', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'mayonesa_granel', name: 'MAYONESA A GRANEL', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'mayonesa_individual', name: 'MAYONESA INDIVIDUAL', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'medialuna_grasa', name: 'MEDIALUNA DE GRASA X 240 UND', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'medialuna_manteca', name: 'MEDIALUNA DE MANTECA X 180 UND', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'mezcla_huevo_leche', name: 'MEZCLA HUEVO/LECHE', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'mix_ensalada', name: 'MIXDE ENSALADA', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'mostaza_miel', name: 'MOSTAZA CON MIEL', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'mostaza_miel_individual', name: 'MOSTAZA CON MIEL INDIVIDUAL', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'mostaza_individual', name: 'MOSTAZA INDIVIDUAL .', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'pano_blanco', name: 'PAÑO BLANCO X 300 UN', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'pano_azul', name: 'PAÑO AZUL', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'pano_rojo', name: 'PAÑO ROJO', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'pan_porteno', name: 'PAN PORTENO', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'panal_membrillo', name: 'PANAL MEMBRILLO X 72 UND', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'panceta_kfc', name: 'PANCETA KFC', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'papas_fritas_kfc', name: 'PAPAS FRITAS KFC C7 X 18 KG', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'papel_antigrasa_blanco', name: 'PAPEL ANTIGRASA BLANCO', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'papel_antigrasa_generico', name: 'PAPEL ANTIGRASA GENERICO CAJA X 4000', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'papel_antigrasa_sandwich_2', name: 'PAPEL ANTIGRASA SANDWICH KFC 2', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'papel_manos', name: 'PAPEL DE MANOS (TO)', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'papel_film', name: 'PAPEL FILM (ROLLO)', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'papel_higienico', name: 'PAPEL HIGIENICO', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'papel_siliconado', name: 'PAPEL SILICONADO X 500 UND', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'pepino_acanalado', name: 'PEPINO ACANALADO X 620 UND', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'portavasos_kfc', name: 'PORTAVASOS KFC X 200 UND', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'pote_360_impreso', name: 'POTE 360 IMPRESO KFC 2', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'pote_impreso_avalancha', name: 'POTE IMPRESO AVALANCHA KFC 2', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'queso_cheddar_bolsa', name: 'QUESO CHEDDAR EN BOLSA', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'queso_cheddar_fetas', name: 'QUESO CHEDDAR EN FETAS 2', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'rejilla_pastelera', name: 'REJILLA PASTELERA X 72 UND', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'revolvedor_cafe_madera', name: 'REVOLVEDOR CAFE MADERA', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'rollo_impresora_fiscal_generico', name: 'ROLLO IMPRESORA FISCAL GENERICO 2', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'rollo_impresora_fiscal_kiosco', name: 'ROLLO IMPRESORA FISCAL KIOSCO', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'sal_granel', name: 'SAL A GRANEL', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'sal_sobre_individual', name: 'SAL SOBRE INDIVIDUAL KFC', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'salsa_barbacoa_granel', name: 'SALSA BARBACOA A GRANEL', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'salsa_barbacoa_individual', name: 'SALSA BARBACOA INDIVIDUAL', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'salsa_chocolate', name: 'SALSA DE CHOCOLATE', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'salsa_ddl_5kg', name: 'SALSA DE DULCE DE LECHE X 5KG', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'salsa_picante_granel', name: 'SALSA PICANTE A GRANEL', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'salsa_picante_individual', name: 'SALSA PICANTE INDIVIDUAL', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'seasoning_or', name: 'SEASONING OR', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'servilletas_30x30', name: 'SERVILLETAS 30X30', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'servilletas_cono', name: 'SERVILLETAS PARA CONO', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'sobre_kfc', name: 'SOBRE KFC X 1000 UND', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'sobres_billetes', name: 'SOBRES PARA BILLETES', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'sticker_amarillo', name: 'STICKER REDONDO AMARILLO', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'sticker_azul', name: 'STICKER REDONDO AZUL', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'sticker_naranja', name: 'STICKER REDONDO NARANJA', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'sticker_negro', name: 'STICKER REDONDO NEGRO', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'sticker_rojo', name: 'STICKER REDONDO ROJO', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'sticker_verde', name: 'STICKER REDONDO VERDE', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'sticker_vencimiento', name: 'STICKER VENCIMIENTO', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'sundae_kfc', name: 'SUNDAE KFC 7.25 OZ X 2000 UND', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'tapa_bucket_kfc', name: 'TAPA BUCKET KFC X 2150 UND', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'tapa_caja_big_box', name: 'TAPA CAJA BIG BOX', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'tapa_caja_snack', name: 'TAPA CAJA SNACK KFC X 250 UND', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'tapa_dipper', name: 'TAPA DIPPER', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'tapa_vaso_cafe_8_12oz', name: 'TAPA VASO CAFE 8 Y 12 OZ X 2000 UND', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'tapa_vaso_domo_11oz', name: 'TAPA VASO DOMO 11OZ KFC X 2000 U', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'tapa_vaso_gaseosa_16oz', name: 'TAPA VASO GASEOSA 16OZ', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'tapa_vaso_gaseosa_12oz', name: 'TAPAÂ VASO GASEOSA 12OZ', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'te_intizen_ilumine', name: 'TE INTIZEN ILUMINE (ROJO)', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'te_intizen_variedad', name: 'TE INTIZEN PACK VARIEDAD', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'tenedor', name: 'TENEDOR', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'tomate', name: 'TOMATE', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'vaso_cafe_8oz', name: 'VASO CAFE 8 OZ KFC', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'vaso_cortesia', name: 'VASO CORTESIA KFC', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'vaso_gaseosa_12oz', name: 'VASO GASEOSA 12OZ KFC A', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'vaso_gaseosa_16oz', name: 'VASO GASEOSA 16OZ KFC A', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'vaso_gaseosa_21oz', name: 'VASO GASEOSA 21OZ KFC', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'vaso_cafe_12oz', name: 'VASO?CAFE 12 OZ KFC X 1000', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'vinagre_manzana_individual', name: 'VINAGRE DE MANZANA INDIVIDUAL', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' },
    { id: 'vinagreta_individual', name: 'VINAGRETA INDIVIDUAL', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.' }
].map(item => ({ ...item, unitsPerBag: 1, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paq.', caseOrderUnit: 'Paq.'}));


export const SUPPLIER_CONFIG: Suppliers = {
  [SupplierKey.Planta]: {
    name: "Planta",
    localStorageKey: "kfcPlantaOrderHistory",
    products: [
      { id: 'alitas', name: 'Alitas', unitsPerBag: 24, bagsPerCase: 14, unitName: 'Uds', packageOrderUnit: 'Bolsas', caseOrderUnit: 'Cajones' },
      { id: 'filete', name: 'Filete', unitsPerBag: 14, bagsPerCase: 12, unitName: 'Uds', packageOrderUnit: 'Bolsas', caseOrderUnit: 'Cajones' },
      { id: 'ruster', name: 'Ruster', unitsPerBag: 30, bagsPerCase: 10, unitName: 'Uds', packageOrderUnit: 'Bolsas', caseOrderUnit: 'Cajones' },
      { id: 'pieza_crispy', name: 'Pieza Crispy', unitsPerBag: 18, bagsPerCase: 8, unitName: 'Uds', packageOrderUnit: 'Bolsas', caseOrderUnit: 'Cajones' },
      { id: 'pieza_original', name: 'Pieza Original', unitsPerBag: 18, bagsPerCase: 8, unitName: 'Uds', packageOrderUnit: 'Bolsas', caseOrderUnit: 'Cajones' },
      { id: 'pop', name: 'Pop (1kg)', unitsPerBag: 1, bagsPerCase: 22, unitName: 'Kg', packageOrderUnit: 'Bolsas', caseOrderUnit: 'Cajones' },
      { id: 'strips', name: 'Strips', unitsPerBag: 18, bagsPerCase: 20, unitName: 'Uds', packageOrderUnit: 'Bolsas', caseOrderUnit: 'Cajones' }
    ]
  },
  [SupplierKey.Fargo]: {
    name: "Fargo",
    localStorageKey: "kfcFargoOrderHistory",
    products: [
      { id: 'pan_regular', name: 'Pan Regular', unitsPerBag: 60, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paquetes', caseOrderUnit: 'Paquetes' },
      { id: 'pan_brioche', name: 'Pan Brioche', unitsPerBag: 60, bagsPerCase: 1, unitName: 'Uds', packageOrderUnit: 'Paquetes', caseOrderUnit: 'Paquetes' }
    ]
  },
  [SupplierKey.ReginaldLee]: {
    name: "Reginald Lee",
    localStorageKey: "kfcReginaldLeeOrderHistory",
    products: [
      { id: 'coca_botella', name: 'Coca Cola Botella', unitsPerBag: 12, bagsPerCase: 1, unitName: 'Botellas', packageOrderUnit: 'Paquetes', caseOrderUnit: 'Paquetes' },
      { id: 'coca_cero_botella', name: 'Coca Cola Cero Botella', unitsPerBag: 12, bagsPerCase: 1, unitName: 'Botellas', packageOrderUnit: 'Paquetes', caseOrderUnit: 'Paquetes' },
      { id: 'aq_manzana', name: 'Aquarius Manzana', unitsPerBag: 8, bagsPerCase: 1, unitName: 'Botellas', packageOrderUnit: 'Paquetes', caseOrderUnit: 'Paquetes' },
      { id: 'aq_pomelo', name: 'Aquarius Pomelo', unitsPerBag: 8, bagsPerCase: 1, unitName: 'Botellas', packageOrderUnit: 'Paquetes', caseOrderUnit: 'Paquetes' },
      { id: 'aq_pera', name: 'Aquarius Pera', unitsPerBag: 8, bagsPerCase: 1, unitName: 'Botellas', packageOrderUnit: 'Paquetes', caseOrderUnit: 'Paquetes' },
      { id: 'agua_botella', name: 'Agua Botella', unitsPerBag: 12, bagsPerCase: 1, unitName: 'Botellas', packageOrderUnit: 'Paquetes', caseOrderUnit: 'Paquetes' },
      { id: 'jarabe_coca', name: 'Jarabe Coca Cola (10L)', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Envases', packageOrderUnit: 'Envases', caseOrderUnit: 'Envases' },
      { id: 'jarabe_coca_cero', name: 'Jarabe Coca Cero (10L)', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Envases', packageOrderUnit: 'Envases', caseOrderUnit: 'Envases' },
      { id: 'jarabe_fanta', name: 'Jarabe Fanta (10L)', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Envases', packageOrderUnit: 'Envases', caseOrderUnit: 'Envases' },
      { id: 'jarabe_sprite', name: 'Jarabe Sprite (10L)', unitsPerBag: 1, bagsPerCase: 1, unitName: 'Envases', packageOrderUnit: 'Envases', caseOrderUnit: 'Envases' },
      { id: 'jugo_naranja', name: 'Jugo Cepita Naranja', unitsPerBag: 6, bagsPerCase: 1, unitName: 'Unidades', packageOrderUnit: 'Paquetes', caseOrderUnit: 'Paquetes' },
      { id: 'jugo_manzana', name: 'Jugo Cepita Manzana', unitsPerBag: 6, bagsPerCase: 1, unitName: 'Unidades', packageOrderUnit: 'Paquetes', caseOrderUnit: 'Paquetes' },
      { id: 'jugo_multifruta', name: 'Jugo Cepita Multifruta', unitsPerBag: 6, bagsPerCase: 1, unitName: 'Unidades', packageOrderUnit: 'Paquetes', caseOrderUnit: 'Paquetes' }
    ]
  },
  [SupplierKey.Axion]: {
    name: "Axion",
    localStorageKey: "kfcAxionOrderHistory",
    localStorageItemsKey: "kfcAxionItemsList",
    products: [] // Loaded dynamically
  }
};

export const LOCAL_STORAGE_THEME_KEY = 'kfc_theme_react';
export const LOCAL_STORAGE_SPECIAL_REMINDERS_KEY = 'kfcSpecialReminders_react';
export const LOCAL_STORAGE_AXION_ITEMS_KEY = 'kfcAxionItemsList_react';

export const KFC_RED = '#D92200';
export const KFC_RED_DARK_HOVER = '#FF6259';
export const KFC_RED_HOVER = '#B91C00';
export const KFC_RED_DARK = '#FF4136';

export const SUPPLIER_OPTIONS = [
  { value: SupplierKey.Planta, label: 'Planta' },
  { value: SupplierKey.Fargo, label: 'Fargo' },
  { value: SupplierKey.ReginaldLee, label: 'Reginald Lee' },
  { value: SupplierKey.Axion, label: 'Axion' },
  { value: 'Otro', label: 'Otro (especificar)' },
];

export const DATE_OPTIONS: Intl.DateTimeFormatOptions = { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' };
